name = "alog-gunzip-worker"
main = "src/index.ts"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

[[queues.consumers]]
queue = "alog-gunzip-queue"
max_batch_size = 100
max_batch_timeout = 5

[[r2_buckets]]
binding = "LOGPUSH_BUCKET"
bucket_name = "alog-gzip"

[[r2_buckets]]
binding = "MOUNT_BUCKET"
bucket_name = "alog-cloud"